### PR TITLE
Added CSS selectors for likes and dislikes 

### PR DESCRIPTION
**Pull request by cyaohiri**
Added CSS selectors for likes and dislikes to work with the new YouTube layout

### CODE REVIEW

**Comment by krydos** [comment]
Thanks @cyaohiri
I didn't change anything in this extension after youtube removed dislikes and updated their UI. 

I'll let you know when this is landed to chrome and firefox extension store.

**Comment by krydos** [comment]
Actually I had to revert it after merge. 
The main point of this extension was to keep like and dislike buttons visible for users so they still can vote and hide the ratio of likes/dislikes at the same time. 

With the latest youtube update it seems like this extension isn't needed anymore really. 

But I'm not opposed of removing the amount of likes though for those who use it. 

I guess this selector `#segmented-like-button > ytd-toggle-button-renderer > yt-button-shape > button > div.cbox.yt-spec-button-shape-next--button-text-content` is what we can hide. 

@cyaohiri does it sounds ok for you?

**Comment by cyaohiri** [comment]
I think that would make the most sense. With the new layout, the only thing that makes sense to hide is the number of likes,

**Comment by krydos** [comment]
thanks @cyaohiri, I just published the new version of this extension. Likes counter should disappear now.

**Pull request merged**
